apiVersion: v1
kind: Service
metadata:
  name: mypage-svc
spec:
  selector:
    app: mypage-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypage-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypage-app
  template:
    metadata:
      name: mypage-pod
      labels:
        app: mypage-app
    spec:
      containers:
      - name: mypage-con
        image: 178020491921.dkr.ecr.ap-northeast-2.amazonaws.com/mypageapp:1.0