apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "reservation-ingress"
  labels:
    app.kubernetes.io/name: "reservation-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /reservations
 
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: reservation-svc
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-svc
spec:
  type: LoadBalancer
  selector:
    app: reservation-app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservation-app
  template:
    metadata:
      name: reservation-pod
      labels:
        app: reservation-app
    spec:
      containers:
      - name: reservation-con
        image: 178020491921.dkr.ecr.ap-northeast-2.amazonaws.com/reservationapp:2.0